### ISSUE TITLE
AttributeError: 'DataLoader' object has no attribute 'read_routes'

### ISSUE THREAD

**Issue by linny006** [marcjulianschwarz/watchlib#1]
read_routes is not defined in DataLoader

**Comment by marcjulianschwarz** [comment]
Did you use the DataLoader demo notebook?
If yes, the demo notebooks haven't been updated for quite a while that's why they don't work right now.

I just updated the DataLoader demo notebook for the newest watchlib version. Everything should work now.

**Comment by marcjulianschwarz** [comment]
But be aware, I am still working on the other two notebooks which currently **don't** work.

**Comment by alistaitsacle** [comment]
Yes, none of these three notebooks work.

**Comment by marcjulianschwarz** [comment]
@alistaitsacle yes, the whole package is still a work in progress, so things do change quite a lot. That’s why the notebooks are not always up to date.
I can let you know when all three of them are updated to work with the newest version.

**Comment by marcjulianschwarz** [comment]
A lot of issues with the demonstrator and loading of ECGs have now been fixed. You may want to try out the new version.
