### ISSUE TITLE
Incomplete code, no CacheHandler

### ISSUE THREAD

**Issue by alistaitsacle** [marcjulianschwarz/watchlib#2]
First of all thank you for your sharing, but I think your sharing is very casual, the notebook is not available, and the project code is also incomplete, such as missing CacheHandler. I tried to test but can't work.

**Comment by alistaitsacle** [comment]
There is CacheHandler in the code, I test not working, I am checking

**Comment by marcjulianschwarz** [comment]
This package is still a work in progress and is therefore changing a lot, sometimes I don’t have the time to update the demo notebooks accordingly.
Currently I am additionally working on a „beta“ documentation. It will probably replace all demos soon.

**Comment by alistaitsacle** [comment]
👍  Looking forward to your update

**Comment by marcjulianschwarz** [comment]
Hi @alistaitsacle, 
I just found out that I need to rewrite a lot of code as different apple watches seem to produce different datasets. If you would like to help out you could join me on Discord and maybe even send a sample dataset from your Apple Watch. That way I can more easily test all functionalities.
Here is the link: 
https://discord.gg/TYmZkn9ezf
