### ISSUE TITLE
I am facing issues

### ISSUE THREAD

**Issue by shazinabbas** [marcjulianschwarz/watchlib#7]
How can I contact you?

**Comment by marcjulianschwarz** [comment]
You can contact me here via this issue.

**Comment by marcjulianschwarz** [comment]
I'm currently rewriting the whole library. I'll make the repository for the new version available to the public in a few days. Stay tuned!

**Comment by marcjulianschwarz** [comment]
https://github.com/marcjulianschwarz/watchml
